change config base64 in secrets

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -76,7 +76,8 @@ jobs:
       - name: Configure Kubeconfig
         run: |
           mkdir -p ~/.kube
-          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
+          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config || echo "Base64 decode failed"
+          cat ~/.kube/config || echo "Kubeconfig file is empty"
           chmod 600 ~/.kube/config
           export KUBECONFIG=~/.kube/config
 
